version: "3.9"
services:
  web:
    # image: kudligi97/urlshortener:main
    build: .
    ports:
      - "5000"
    volumes:
      - ./persist:/go/app/persist
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "9090:9090"
