version: "3.9"
services:
  web:
    # image: kudligi97/urlshortener:main
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ./persist:/go/app/persist
  redis:
    image: redis
    ports:
      - "6379:6379"
